FROM ruby:2.2-alpine

WORKDIR /app
COPY . /app

RUN apk add --no-cache build-base && \
    bundle install && \
    apk del build-base && \
    rm -rf /root/.bundle

ENV POST_SERVICE_HOST post \
    POST_SERVICE_PORT 5000 \
    COMMENT_SERVICE_HOST comment \
    COMMENT_SERVICE_PORT 9292

CMD ["puma"]
